#!/bin/bash

# pdiff - Process inputs, then diff
#
# pdiff applies an aribtrary bash command/transformation to two input files, then diffs
# the results. For example, to diff two .py files, but looking at roughly only comments:
#   pdiff 'grep "#"' one.py two.py


set -euo pipefail

slugify() {
  iconv -t ascii//TRANSLIT | sed -E 's/[~\^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+\|-+$//g' | sed -E 's/^-+//g' | sed -E 's/-+$//g' | tr A-Z a-z
}

cmd="$1"
left="$2"
right="$3"
gitOpts="${4:-}"

runCmd() { eval "$cmd" || true; }
processedLeft=$(mktemp /tmp/pdiff.$(echo "$left" | slugify).XXXX)
cat "$left" | runCmd > "$processedLeft"
processedRight=$(mktemp /tmp/pdiff.$(echo "$right" | slugify).XXXX)
cat "$right" | runCmd > "$processedRight"
echo "Diffing $processedLeft and $processedRight"
git diff $gitOpts "$processedLeft" "$processedRight"
